management:
  endpoints:
    web:
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: '%d %-5level %logger : %msg%n'
    file: '%d %-5level [%thread] %logger : %msg%n'
  level:
    org.springframework.web: ERROR
    com.gft.managementservice*: DEBUG

spring:
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/management?autoreconnect=true"
    password: "password"
    username: "sa"
  jpa:
    show-sql: true
    generate-ddl: false
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: validate
    open-in-view: false

flyway:
   url: jdbc:mysql://localhost:3306/mysql
   schemas: management
   user: "sa"
   password: "password"

server:
  port: 8000
