version: "3.9"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 3
    # networks:
    #   - grpc-demo-network
  
  # java-employee-rest-api:
  #   build:
  #     context: ./java-employee-rest-api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #       - mysql
  #   networks:
  #       - grpc-demo-network

  # java-certificate-rest-api:
  #   build:
  #     context: ./java-certificate-rest-api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #       - mysql
  #   networks:
  #       - grpc-demo-network

  # go-grpc:
  #   build:
  #     context: ./go-grpc
  #     dockerfile: Dockerfile
  #   ports:
  #     - "50051:50051"
  #   networks:
  #       - grpc-demo-network

volumes:
  mysql_data:

# networks:
#   grpc-demo-network:
