version: "3.9"

services:
  java-rest-api:
    build:
      context: ./java-rest-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  java-product-service:
    build:
      context: ./java-product-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  java-order-service:
    build:
      context: ./java-order-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"

  go-grpc:
    build:
      context: ./go-grpc
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
  
networks:
  default:
    name: grpc-demo-network
    driver: bridge
