openapi: 3.0.0
info:
  title: Employee Service
  description: Employee Service API
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /employees:
    get:
      summary: Get all employees
      responses:
        '200':
          description: A list of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
  /employees/{id}:
    get:
      summary: Get employee by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: An employee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '404':
          description: Not found
components:
  schemas:
    Employee:
      type: object
      required:
        - id
        - name
        - employeeType
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        employeeType:
          type: string
          enum:
          - FULL_TIME
          - PART_TIME
        dob:
          type: string
          format: date
        certificates:
          type: array
          items:
            $ref: '#/components/schemas/Certificate'
    Certificate:
      type: object
      required:
        - id
        - name
        - grade
        - expiredDate
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        grade:
          type: string
        score:
          type: number
          format: float
        expiredDate:
          type: string
          format: date