apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-grpc
  template:
    metadata:
      name: go-grpc
      labels:
        app: go-grpc
    spec:
      containers:
      - name: go-grpc
        image: grpc-go-grpc:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
          - name: VERSION
            value: "v1"
---
apiVersion: v1
kind: Service
metadata:
  name: go-grpc
  labels:
    app: go-grpc
spec:
  type: ClusterIP
  ports:
    - port: 50051
      name: http
  selector:
    app: go-grpc