openapi: 3.0.0
info:
  title: Certificate Service
  description: Certificate Service API
  version: 1.0.0
servers:
  - url: http://localhost:8001/v1
paths:
  /certificates/{employeeId}:
    get:
      summary: Get certificates of an employee
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A list of certificates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Certificate'
components:
  schemas:
    Certificate:
      type: object
      required:
        - id
        - name
        - grade
        - expiredDate
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        grade:
          type: string
        score:
          type: number
          format: float
        expiredDate:
          type: string
          format: date